import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BrowserRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { api, Post, setAccessToken, User } from './api';
import './styles.css';

const client = new QueryClient();
type Session = { user: User | null; loading: boolean; setUser: (u: User | null) => void };
const SessionContext = React.createContext<Session>(null!);
const useSession = () => React.useContext(SessionContext);

function SessionProvider({children}:{children:React.ReactNode}) { const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true); useEffect(()=>{ api.me().then(setUser).catch(()=>setUser(null)).finally(()=>setLoading(false)); },[]); return <SessionContext.Provider value={{user,loading,setUser}}>{children}</SessionContext.Provider>; }
function Guard({children}:{children:React.ReactNode}) { const {user,loading}=useSession(); if(loading) return <Centered text="思い出を読み込んでいます…"/>; return user ? children : <Navigate to="/login" replace/>; }
function Centered({text}:{text:string}) { return <main className="center"><span className="spinner"/><p>{text}</p></main>; }

function AuthPage({register=false}:{register?:boolean}) { const nav=useNavigate(); const {setUser}=useSession(); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);try{const result=register?await api.register({displayName:fd.get('name'),email:fd.get('email'),password:fd.get('password'),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}):await api.login({email:fd.get('email'),password:fd.get('password')});setAccessToken(result.accessToken);setUser(result.user);nav('/');}catch(x){setError(x instanceof Error?x.message:'失敗しました');}finally{setBusy(false)}} return <main className="auth-shell"><section className="brand-panel"><span className="eyebrow">YOUR DAYS, KEPT CLOSE</span><h1>Memory</h1><p>今日の一枚が、いつか大切な記憶になる。</p></section><form className="auth-card" onSubmit={submit}><h2>{register?'アカウントを作る':'おかえりなさい'}</h2><p className="muted">{register?'あなたの思い出の場所をはじめましょう。':'思い出の続きを見にいきましょう。'}</p>{register&&<label>表示名<input name="name" maxLength={80} required autoComplete="name"/></label>}<label>メールアドレス<input name="email" type="email" required autoComplete="email"/></label><label>パスワード<input name="password" type="password" minLength={10} required autoComplete={register?'new-password':'current-password'}/></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy}>{busy?'送信しています…':register?'はじめる':'ログイン'}</button><p className="switch">{register?'すでに登録済みですか？':'はじめてですか？'} <NavLink to={register?'/login':'/register'}>{register?'ログイン':'新規登録'}</NavLink></p></form></main>; }

function Layout(){const {user,setUser}=useSession();const nav=useNavigate();async function logout(){await api.logout();setAccessToken(null);setUser(null);nav('/login')}return <div className="app"><header><NavLink className="logo" to="/">Memory<span>●</span></NavLink><nav><NavLink to="/">ホーム</NavLink><NavLink to="/calendar">カレンダー</NavLink><NavLink to="/memories/today">一年前の今日</NavLink></nav><div className="profile"><span>{user?.displayName.slice(0,1)}</span><button className="text-button" onClick={logout}>ログアウト</button></div></header><Routes><Route index element={<Feed/>}/><Route path="new" element={<NewPost/>}/><Route path="calendar" element={<Calendar/>}/><Route path="memories/today" element={<Memories/>}/><Route path="profile" element={<Profile/>}/></Routes><NavLink className="fab" to="/new" aria-label="新しい投稿">＋</NavLink></div>}
function PostCard({post}:{post:Post}){const qc=useQueryClient();const remove=useMutation({mutationFn:()=>api.deletePost(post.id),onSuccess:()=>qc.invalidateQueries({queryKey:['posts']})});return <article className="post"><div className="post-date"><strong>{new Date(post.occurredOn+'T00:00:00').toLocaleDateString('ja-JP',{month:'long',day:'numeric'})}</strong><span>{post.occurredOn.slice(0,4)}</span></div>{post.media[0]&&(post.media[0].kind==='video'?<video controls src={post.media[0].url}/>:<img src={post.media[0].url} alt={post.caption??'思い出の写真'}/>)}<div className="post-copy"><p>{post.caption||'この日の思い出'}</p><button className="text-button danger" onClick={()=>remove.mutate()}>削除</button></div></article>}
function Feed(){const q=useQuery({queryKey:['posts'],queryFn:()=>api.posts()});if(q.isPending)return <Centered text="タイムラインを読み込んでいます…"/>;return <main className="content"><div className="hero"><span className="eyebrow">MY MOMENTS</span><h1>思い出を、<br/>日々のそばに。</h1><p>写真と一緒に、その日の気持ちを残しましょう。</p></div><section className="section-title"><h2>最近の思い出</h2><NavLink to="/new">＋ 新しい投稿</NavLink></section>{q.error&&<p className="error">{q.error.message}</p>}<div className="grid">{q.data?.items.map(p=><PostCard key={p.id} post={p}/>)}</div>{q.data?.items.length===0&&<div className="empty"><h3>最初の思い出を残しましょう</h3><p>右下の＋ボタンから写真を投稿できます。</p></div>}</main>}
function NewPost(){const nav=useNavigate();const [preview,setPreview]=useState('');const [error,setError]=useState('');const mutation=useMutation({mutationFn:api.createPost,onSuccess:()=>nav('/')});function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);mutation.mutate(fd,{onError:e=>setError(e.message)})}return <main className="narrow"><NavLink to="/" className="back">← 戻る</NavLink><h1>今日を残す</h1><form className="post-form" onSubmit={submit}><label className="drop">{preview?<img src={preview} alt="プレビュー"/>:<><b>写真や動画を選択</b><small>JPEG・PNG・WebP・MP4 / 25MBまで</small></>}<input name="media" type="file" accept="image/jpeg,image/png,image/webp,video/mp4" required onChange={e=>{const f=e.target.files?.[0];if(f)setPreview(URL.createObjectURL(f))}}/></label><label>思い出の日<input name="occurredOn" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>ひとこと<textarea name="caption" maxLength={2000} rows={4} placeholder="この日のことを書いてみましょう"/></label>{error&&<p className="error">{error}</p>}<button disabled={mutation.isPending}>{mutation.isPending?'保存しています…':'思い出を保存'}</button></form></main>}
function Memories(){const q=useQuery({queryKey:['memories'],queryFn:api.memories});return <main className="content"><div className="hero small"><span className="eyebrow">ON THIS DAY</span><h1>一年前の今日</h1><p>時間を越えて、あの日の自分に会いにいこう。</p></div>{q.isPending?<Centered text="思い出を探しています…"/>:<div className="grid">{q.data?.map(p=><PostCard key={p.id} post={p}/>)}</div>}{q.data?.length===0&&<div className="empty"><h3>この日の思い出はまだありません</h3><p>来年ここで会えるように、今日を残してみませんか。</p></div>}</main>}
function Calendar(){const now=new Date();const [cursor,setCursor]=useState(new Date(now.getFullYear(),now.getMonth(),1));const q=useQuery({queryKey:['calendar',cursor.getFullYear(),cursor.getMonth()],queryFn:()=>api.calendar(cursor.getFullYear(),cursor.getMonth()+1)});const counts=new Map(q.data?.map(x=>[Number(x.date.slice(-2)),x.count]));const blanks=new Date(cursor.getFullYear(),cursor.getMonth(),1).getDay();const days=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();return <main className="narrow calendar-page"><div className="month-nav"><button className="text-button" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}>←</button><h1>{cursor.getFullYear()}年 {cursor.getMonth()+1}月</h1><button className="text-button" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}>→</button></div><div className="calendar">{'日月火水木金土'.split('').map(x=><b key={x}>{x}</b>)}{Array.from({length:blanks},(_,i)=><i key={'b'+i}/>)}{Array.from({length:days},(_,i)=><div key={i+1} className={counts.has(i+1)?'has-memory':''}><span>{i+1}</span>{counts.has(i+1)&&<small>{counts.get(i+1)}件</small>}</div>)}</div></main>}
function Profile(){const {user}=useSession();return <main className="narrow"><h1>プロフィール</h1><div className="profile-card"><div className="avatar">{user?.displayName.slice(0,1)}</div><h2>{user?.displayName}</h2><p>{user?.email}</p><span className="badge">{user?.membership==='premium'?'Premium':'Free'}</span></div></main>}
function App(){return <BrowserRouter><SessionProvider><Routes><Route path="/login" element={<AuthPage/>}/><Route path="/register" element={<AuthPage register/>}/><Route path="/*" element={<Guard><Layout/></Guard>}/></Routes></SessionProvider></BrowserRouter>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><App/></QueryClientProvider></React.StrictMode>);
