import { Alert, Pressable, ScrollView, StyleSheet, Text } from "react-native";
import { Body, Button, Card, Title } from "../components/atoms";
import { api } from "../shared/api";
import { Session } from "../shared/session";
import { colors, spacing } from "../shared/theme";

export function AccountSettingsScreen({ session, onBack, onDeleted }: { session: Session; onBack: () => void; onDeleted: () => void }) {
  const ja = session.user.preferredLanguage === "ja";
  const remove = () => Alert.alert(ja ? "アカウントを削除しますか？" : "Delete your account?", ja ? "直ちにログインできなくなります。投稿メディアの物理削除は本番用削除ジョブの接続後に実行されます。この操作は元に戻せません。" : "You will immediately lose access. Physical media removal will run after the production deletion job is connected. This cannot be undone.", [{ text: ja ? "戻る" : "Back", style: "cancel" }, { text: ja ? "削除する" : "Delete", style: "destructive", onPress: async () => { try { await api.deleteAccount(session); onDeleted(); } catch (e) { Alert.alert(ja ? "削除できませんでした" : "Could not delete account", e instanceof Error ? e.message : "Error"); } } }]);
  return <ScrollView contentContainerStyle={styles.container}><Pressable onPress={onBack}><Text style={styles.back}>‹ {ja ? "プロフィール" : "Profile"}</Text></Pressable><Title>{ja ? "アカウント管理" : "Account"}</Title><Card><Text style={styles.section}>{ja ? "メールアドレス確認" : "Email verification"}</Text><Body>{session.user.email}</Body><Body muted>{ja ? "確認メールの送信は、メール配信サービス接続後に利用できます。" : "Verification email delivery will be available after the email service is connected."}</Body><Button secondary label={ja ? "メール確認は準備中" : "Verification coming soon"} onPress={() => undefined} disabled /></Card><Card><Text style={styles.section}>{ja ? "パスワード再設定" : "Password reset"}</Text><Body muted>{ja ? "再設定メールの送信基盤は準備中です。利用可能になるまで、現在のパスワードを安全に保管してください。" : "Password reset email delivery is being prepared. Keep your current password safe until it is available."}</Body><Button secondary label={ja ? "パスワード再設定は準備中" : "Password reset coming soon"} onPress={() => undefined} disabled /></Card><Card><Text style={styles.dangerTitle}>{ja ? "アカウント削除" : "Delete account"}</Text><Body muted>{ja ? "削除後はアカウントと投稿へアクセスできません。" : "After deletion, you cannot access your account or posts."}</Body><Button danger label={ja ? "アカウントを削除" : "Delete account"} onPress={remove} /></Card></ScrollView>;
}
const styles = StyleSheet.create({ container: { padding: spacing.lg, gap: spacing.lg }, back: { color: colors.primary, fontSize: 16 }, section: { color: colors.text, fontSize: 18, fontWeight: "700" }, dangerTitle: { color: colors.danger, fontSize: 18, fontWeight: "700" } });
