import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Body, Card, Title } from "../components/atoms";
import { api, resolveMediaUrl } from "../shared/api";
import { Session } from "../shared/session";
import { CalendarDay, Post } from "../shared/types";
import { colors, spacing } from "../shared/theme";

const weekJa = ["日", "月", "火", "水", "木", "金", "土"];
const weekEn = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const iso = (year: number, month: number, day: number) => `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;

export function CalendarScreen({ session }: { session: Session }) {
  const today = new Date(); const [cursor, setCursor] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [days, setDays] = useState<CalendarDay[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [selectedDate, setSelectedDate] = useState<string | null>(null); const [selectedPosts, setSelectedPosts] = useState<Post[]>([]);
  const ja = session.user.preferredLanguage === "ja"; const year = cursor.getFullYear(), month = cursor.getMonth() + 1;
  useEffect(() => { setLoading(true); api.calendar(session, year, month).then(setDays).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [session, year, month]);
  const counts = useMemo(() => new Map(days.map(d => [d.date, d.count])), [days]); const first = new Date(year, month - 1, 1).getDay(); const total = new Date(year, month, 0).getDate();
  const formatPostedAt = (createdAt: string) => new Intl.DateTimeFormat(ja ? "ja-JP" : "en-US", {
    year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit",
    timeZone: session.user.timezone,
  }).format(new Date(createdAt));
  const openDay = async (date: string, count: number) => { if (!count) return; setSelectedDate(date); try { setSelectedPosts(await api.day(session, date)); } catch (e) { setError(e instanceof Error ? e.message : "Error"); } };
  return <ScrollView contentContainerStyle={styles.container}><View style={styles.header}><View><Title>{ja ? `${year}年${month}月` : cursor.toLocaleDateString("en", { month: "long", year: "numeric" })}</Title><Body muted>{ja ? "一年後にひらいた思い出" : "Memories opened one year later"}</Body></View><View style={styles.monthButtons}><Pressable onPress={() => setCursor(new Date(year, month - 2, 1))}><Text style={styles.arrow}>‹</Text></Pressable><Pressable onPress={() => setCursor(new Date(year, month, 1))}><Text style={styles.arrow}>›</Text></Pressable></View></View><Card>{loading ? <ActivityIndicator color={colors.primary} /> : <><View style={styles.week}>{(ja ? weekJa : weekEn).map(x => <Text key={x} style={styles.weekLabel}>{x}</Text>)}</View><View style={styles.grid}>{Array.from({ length: first }).map((_, i) => <View key={`blank-${i}`} style={styles.cell} />)}{Array.from({ length: total }).map((_, i) => { const day = i + 1, date = iso(year, month, day), count = counts.get(date) ?? 0; return <Pressable accessibilityRole={count ? "button" : undefined} onPress={() => openDay(date, count)} key={day} style={[styles.cell, selectedDate === date && styles.selectedCell]}><Text style={styles.day}>{day}</Text>{count > 0 && <View style={styles.dots}>{Array.from({ length: Math.min(count, 2) }).map((_, dot) => <View key={dot} style={styles.dot} />)}</View>}</Pressable>; })}</View></>}{!!error && <Text style={styles.error}>{error}</Text>}</Card>{selectedDate && selectedPosts.map(post => <Card key={post.id}>{post.media[0]?.kind === "image" ? <Image source={{ uri: resolveMediaUrl(post.media[0].url), headers: { Authorization: `Bearer ${session.accessToken}` } }} style={styles.memoryImage} /> : <View style={styles.videoMemory}><Text>▶ {ja ? "動画の思い出" : "Video memory"}</Text></View>}<Body>{post.caption || (ja ? "メッセージはありません" : "No message")}</Body><Body muted>{ja ? `${post.occurredOn} の思い出` : `Memory from ${post.occurredOn}`}</Body><Body muted>{ja ? `投稿時刻：${formatPostedAt(post.createdAt)}` : `Posted at ${formatPostedAt(post.createdAt)}`}</Body></Card>)}<Card><Body>{ja ? "今日保存した内容は、10分後から一年間見られません。解禁された思い出だけがこのカレンダーに現れます。" : "Today's memory stays hidden for one year after the 10-minute cancellation period. Only unlocked memories appear here."}</Body></Card></ScrollView>;
}
const styles = StyleSheet.create({ container: { padding: spacing.lg, gap: spacing.lg }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, monthButtons: { flexDirection: "row", gap: spacing.lg }, arrow: { color: colors.primary, fontSize: 38 }, week: { flexDirection: "row" }, weekLabel: { width: `${100 / 7}%`, textAlign: "center", color: colors.muted, fontSize: 12 }, grid: { flexDirection: "row", flexWrap: "wrap" }, cell: { width: `${100 / 7}%`, minHeight: 48, alignItems: "center", paddingTop: spacing.sm, borderRadius: 10 }, selectedCell: { backgroundColor: colors.primarySoft }, day: { color: colors.text }, dots: { flexDirection: "row", gap: 3, marginTop: 5 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.primary }, memoryImage: { width: "100%", aspectRatio: 1, borderRadius: 14 }, videoMemory: { minHeight: 120, alignItems: "center", justifyContent: "center", backgroundColor: colors.primarySoft, borderRadius: 14 }, error: { color: colors.danger } });
